export interface TeamMember {
  id?: number;
  employee_id: string;
  password?: string;
  name: string;
  role: 'Admin' | 'User';
  shift: string;
  shift_type: 'Night Shift' | 'Mid Shift' | 'Day Shift';
  position: string;
  account: string;
  supervisor: string;
  department: string;
  hire_date?: string | null;
  tenure?: number | null;
  traffic_light_status?: string | null;
  avatar_url?: string;
}

export const INITIAL_TEAM_ROSTER: TeamMember[] = [
  {
    employee_id: '1597',
    password: 'CTNP-1597',
    name: 'Nissi-Jeh Reguero',
    role: 'Admin',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Head of Training',
    account: 'Corporate',
    supervisor: 'June Babe Caballes',
    department: 'TQA',
    hire_date: '1/3/2024',
    tenure: 32,
    traffic_light_status: 'GREEN',
  },
  {
    employee_id: '1108',
    password: 'CTNP-1108',
    name: 'Raymundo Alasagas III',
    role: 'Admin',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Head of Quality',
    account: 'Corporate',
    supervisor: 'June Babe Caballes',
    department: 'TQA',
    hire_date: '6/29/2023',
    tenure: 38,
    traffic_light_status: 'GREEN',
  },
  {
    employee_id: '1021',
    password: 'CTNP-1021',
    name: 'Jerico Leyson',
    role: 'Admin',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Process Improvement Specialist - RM',
    account: 'Rocket Money',
    supervisor: 'Julvic Malabat',
    department: 'TQA',
    hire_date: '11/11/2023',
    tenure: 34,
    traffic_light_status: 'GREEN',
  },
  {
    employee_id: '1772',
    password: 'CTNP-1772',
    name: 'Bianca Kaye Ernestine Colonia',
    role: 'User',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Trainer',
    account: 'Corporate',
    supervisor: 'Nissi-Jeh Reguero',
    department: 'TQA',
    hire_date: '5/2/2024',
    tenure: 28,
    traffic_light_status: 'GREEN',
  },
  {
    employee_id: '2385',
    password: 'CTNP-2385',
    name: 'Michelle Yncierto',
    role: 'User',
    shift: '5:00 PM to 2:00 AM',
    shift_type: 'Mid Shift',
    position: 'Trainer',
    account: 'Corporate',
    supervisor: 'Nissi-Jeh Reguero',
    department: 'TQA',
    hire_date: '9/17/2025',
    tenure: 12,
    traffic_light_status: 'GREEN',
  },
  {
    employee_id: '1035',
    password: 'CTNP-1035',
    name: 'Rommel Mendoza',
    role: 'User',
    position: 'Trainer',
    account: 'Corporate',
    supervisor: 'Nissi-Jeh Reguero',
    department: 'TQA',
    hire_date: '11/24/2022',
    tenure: 45,
    traffic_light_status: 'GREEN',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
  },
  {
    employee_id: '1820',
    password: 'CTNP-1820',
    name: 'Ronelyn Baguio',
    role: 'User',
    shift: '11:00 AM to 8:00 PM',
    shift_type: 'Mid Shift',
    position: 'Trainer',
    account: 'Corporate',
    supervisor: 'Nissi-Jeh Reguero',
    department: 'TQA',
    hire_date: '6/3/2024',
    tenure: 27,
    traffic_light_status: 'GREEN',
  },
  {
    employee_id: '836',
    password: 'CTNP-836',
    name: 'Krisland Pepito',
    role: 'User',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Trainer',
    account: 'Rocket Money',
    supervisor: 'Nissi-Jeh Reguero',
    department: 'TQA',
    hire_date: '7/20/2022',
    tenure: 49,
    traffic_light_status: 'GREEN',
  },
  {
    employee_id: '1006',
    password: 'CTNP-1006',
    name: 'Niño Elijah R. Reyes',
    role: 'User',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Trainer',
    account: 'Rocket Money',
    supervisor: 'Nissi-Jeh Reguero',
    department: 'TQA',
    hire_date: '11/7/2022',
    tenure: 46,
    traffic_light_status: 'GREEN',
  },
  {
    employee_id: '1880',
    password: 'CTNP-1880',
    name: 'Kier Ariola',
    role: 'User',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Trainer',
    account: 'Experian',
    supervisor: 'Nissi-Jeh Reguero',
    department: 'TQA',
    hire_date: '7/18/2024',
    tenure: 25,
    traffic_light_status: 'GREEN',
  },
  {
    employee_id: '946',
    password: 'CTNP-946',
    name: 'Vincent Luis Celdran',
    role: 'User',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Trainer',
    account: 'Experian',
    supervisor: 'Nissi-Jeh Reguero',
    department: 'TQA',
    hire_date: '10/5/2022',
    tenure: 47,
    traffic_light_status: 'GREEN',
  },
  {
    employee_id: '2298',
    password: 'CTNP-2298',
    name: 'Nina Joy Briones',
    role: 'User',
    shift: '8:00 PM to 5:00 AM',
    shift_type: 'Night Shift',
    position: 'Trainer',
    account: 'Corporate',
    supervisor: 'Nissi-Jeh Reguero',
    department: 'TQA',
    hire_date: '4/8/2026',
    tenure: 5,
    traffic_light_status: 'GREEN',
  },
  {
    employee_id: '1954',
    password: 'CTNP-1954',
    name: 'Matt Riner Balaba',
    role: 'User',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Trainer',
    account: 'Corporate',
    supervisor: 'Nissi-Jeh Reguero',
    department: 'TQA',
    hire_date: '4/8/2026',
    tenure: 5,
    traffic_light_status: 'GREEN',
  },
  {
    employee_id: '2610',
    password: 'CTNP-2610',
    name: 'Maegan Marie Cabardo',
    role: 'User',
    shift: '8:00 PM to 5:00 AM',
    shift_type: 'Night Shift',
    position: 'Trainer',
    account: 'Corporate',
    supervisor: 'Nissi-Jeh Reguero',
    department: 'TQA',
    hire_date: '6/2/2026',
    tenure: 3,
    traffic_light_status: 'GREEN',
  },
  {
    employee_id: '1898',
    password: 'CTNP-1898',
    name: 'Hezel Mae Domo',
    role: 'User',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Quality Assurance Analyst',
    account: 'Rocket Money',
    supervisor: 'Raymundo Alasagas III',
    department: 'TQA',
    hire_date: null,
    tenure: null,
    traffic_light_status: null,
  },
  {
    employee_id: '1671',
    password: 'CTNP-1671',
    name: 'Janine Codilla',
    role: 'User',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Quality Assurance Analyst',
    account: 'Rocket Money',
    supervisor: 'Raymundo Alasagas III',
    department: 'TQA',
    hire_date: null,
    tenure: null,
    traffic_light_status: null,
  },
  {
    employee_id: '518',
    password: 'CTNP-518',
    name: 'Darin Vic Ecle',
    role: 'User',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Quality Assurance Analyst',
    account: 'Rocket Money',
    supervisor: 'Raymundo Alasagas III',
    department: 'TQA',
    hire_date: null,
    tenure: null,
    traffic_light_status: null,
  },
  {
    employee_id: '770',
    password: 'CTNP-770',
    name: 'Jeffrey Verallo',
    role: 'User',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Quality Assurance Analyst',
    account: 'Rocket Money',
    supervisor: 'Raymundo Alasagas III',
    department: 'TQA',
    hire_date: null,
    tenure: null,
    traffic_light_status: null,
  },
  {
    employee_id: '745',
    password: 'CTNP-745',
    name: 'Steffany Cagape',
    role: 'User',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Quality Assurance Analyst',
    account: 'Experian',
    supervisor: 'Raymundo Alasagas III',
    department: 'TQA',
    hire_date: null,
    tenure: null,
    traffic_light_status: null,
  },
  {
    employee_id: '892',
    password: 'CTNP-892',
    name: 'Hanazaira Peleno',
    role: 'User',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Quality Assurance Analyst',
    account: 'Experian',
    supervisor: 'Raymundo Alasagas III',
    department: 'TQA',
    hire_date: null,
    tenure: null,
    traffic_light_status: null,
  },
  {
    employee_id: '1708',
    password: 'CTNP-1708',
    name: 'Jhonmel Commedador',
    role: 'User',
    shift: '9:00 PM to 6:00 AM',
    shift_type: 'Night Shift',
    position: 'Quality Assurance Analyst',
    account: 'Experian',
    supervisor: 'Raymundo Alasagas III',
    department: 'TQA',
    hire_date: null,
    tenure: null,
    traffic_light_status: null,
  },
];
